// Package onlymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version (devel) DO NOT EDIT.
package onlymodels

// Client defines model for Client.
type Client struct {
	Name string `json:"name"`
}

// Unreferenced defines model for Unreferenced.
type Unreferenced struct {
	Id int `json:"id"`
}
