// Package optionstypealiases provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package optionstypealiases

// Example defines model for Example.
type Example []MyItem

// MyItem defines model for MyItem.
type MyItem struct {
	Age  *int    `json:"age,omitempty"`
	Name *string `json:"name,omitempty"`
}
