// Code generated by specgen from ../../shapes/oneof_additional_properties.yaml. DO NOT EDIT.

// Package matrixv3oneofadditionalproperties is the oneof_additional_properties cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// oneOf over two $ref variants next to a fixed property and untyped additionalProperties.
package matrixv3oneofadditionalproperties

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
