// Code generated by specgen from ../../shapes/allof_nested_own_properties_empty.yaml. DO NOT EDIT.

// Package matrixv2allofnestedownpropertiesempty is the allof_nested_own_properties_empty cell of the aggregate test matrix,
// generated with schema-merging-behavior v2.
//
// allOf over a $ref to a schema that declares a property next to an allOf of an empty object. v2 generates a map, and keeps it one rather than add the property (#2571); v3 generates the property.
//
// The tests here record how v2 handles this shape. A bug fix may change
// the generated code and the tests, but the tests must not be changed to accept
// a regression: code that generated and worked before must keep doing so. A
// commit that changes them must say why.
package matrixv2allofnestedownpropertiesempty

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
