// Code generated by specgen from ../../shapes/allof_untyped_ref_map.yaml. DO NOT EDIT.

// Package matrixv3allofuntypedrefmap is the allof_untyped_ref_map cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// allOf over a $ref to an untyped schema, a $ref to a map (an object with only additionalProperties) and an annotation. The untyped member places no constraint and carries no value of its own, so the composition is the map's type. v1 used to embed both members in a struct, which encodes the value under keys named after their types ({"Untyped": ..., "Labels": {...}}) and leaves the map empty on decoding (#2590).
package matrixv3allofuntypedrefmap

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
