openapi: "3.0.1"
info:
  version: 1.0.0
  title: Type mapping test
paths: {}
components:
  schemas:
    EmployeeDatabaseRecord:
      type: object
      required:
        - ID
        - DateHired
      properties:
        ID:
          type: number
        DateHired:
          type: number
          format: date
