// Package typemapping provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package typemapping

// EmployeeDatabaseRecord defines model for EmployeeDatabaseRecord.
type EmployeeDatabaseRecord struct {
	DateHired CustomDateHandler `json:"DateHired"`
	ID        int64             `json:"ID"`
}
