// Code generated by specgen from ../shapes/allof_nullable_31.yaml. DO NOT EDIT.

// Package matrixallofnullable31 is the allof_nullable_31 cell of the aggregate test matrix.
//
// An OpenAPI 3.1 allOf whose inline member declares `type: [object, "null"]`. Failed with "can not merge incompatible types: [object], [object null]".
package matrixallofnullable31

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
