// Code generated by specgen from ../../shapes/allof_enum_intersection.yaml. DO NOT EDIT.

// Package matrixv3allofenumintersection is the allof_enum_intersection cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// allOf over a $ref to an enum and an enum of its own, which overlap: the composition allows the values in both.
package matrixv3allofenumintersection

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
