// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	// Name Name of the pet
	Name string `json:"name"`

	// Tag Type of the pet
	Tag *string `json:"tag,omitempty"`
}

// Pet defines model for Pet.
type Pet struct {
	// Id Unique id of the pet
	Id int64 `json:"id"`

	// Name Name of the pet
	Name string `json:"name"`

	// Tag Type of the pet
	Tag *string `json:"tag,omitempty"`
}

// FindPets200 defines model for /pets.
type FindPets200 = []Pet

// FindPetsdefault defines model for /pets.
type FindPetsdefault = Error

// AddPet200 defines model for /pets.
type AddPet200 = Pet

// AddPetdefault defines model for /pets.
type AddPetdefault = Error

// DeletePetdefault defines model for /pets/{id}.
type DeletePetdefault = Error

// FindPetByID200 defines model for /pets/{id}.
type FindPetByID200 = Pet

// FindPetByIDdefault defines model for /pets/{id}.
type FindPetByIDdefault = Error

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {
	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = NewPet
