// Package schemasprimitives provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package schemasprimitives

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AliasedDate defines model for AliasedDate.
type AliasedDate = openapi_types.Date

// AnyType1 defines model for AnyType1.
type AnyType1 = any

// AnyType2 AnyType2 represents any type.
//
// This should be an any
type AnyType2 = any

// CustomStringType defines model for CustomStringType.
type CustomStringType = string

// Pet defines model for Pet.
type Pet struct {
	Born   *AliasedDate        `json:"born,omitempty"`
	BornAt *openapi_types.Date `json:"born_at,omitempty"`
}

// ResponseBody defines model for ResponseBody.
type ResponseBody struct {
	Unknown any `json:"unknown,omitempty"`
}
