// Code generated by specgen from ../../shapes/allof_union.yaml. DO NOT EDIT.

// Package matrixv3allofunion is the allof_union cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// allOf over a $ref object schema and an inline oneOf (the union comes out of the merge).
package matrixv3allofunion

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
