openapi: "3.0.0"
info:
  version: 1.0.0
  title: Strict server examples
  description: Contains different content types supported by strict server
servers:
  - url: http://strict.swagger.io/api
paths:
  /json:
    post:
      operationId: JSONExample
      description: JSON is automatically marshalled into structs.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/example"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example"
        400:
          $ref: "#/components/responses/badrequest"
        default:
          description: Unknown error
  /urlencoded:
    post:
      operationId: URLEncodedExample
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/example"
      responses:
        200:
          description: OK
          content:
            application/x-www-form-urlencoded:
              schema:
                $ref: "#/components/schemas/example"
        400:
          $ref: "#/components/responses/badrequest"
        default:
          description: Unknown error
  /multipart:
    post:
      operationId: MultipartExample
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/example"
      responses:
        200:
          description: OK
          content:
            multipart/form-data:
              schema:
                $ref: "#/components/schemas/example"
        400:
          $ref: "#/components/responses/badrequest"
        default:
          description: Unknown error
  /text:
    post:
      operationId: TextExample
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        400:
          $ref: "#/components/responses/badrequest"
        default:
          description: Unknown error
  /unknown:
    post:
      operationId: UnknownExample
      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: byte
      responses:
        200:
          description: OK
          content:
            video/mp4:
              schema:
                type: string
                format: byte
        400:
          $ref: "#/components/responses/badrequest"
        default:
          description: Unknown error
  /multiple:
    post:
      operationId: Multiple request and response types
      description: Shows how to deal with multiple content types in a single request
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/example"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/example"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/example"
          text/plain:
            schema:
              type: string
          image/png:
            schema:
              type: string
              format: byte
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example"
            application/x-www-form-urlencoded:
              schema:
                $ref: "#/components/schemas/example"
            multipart/form-data:
              schema:
                $ref: "#/components/schemas/example"
            text/plain:
              schema:
                type: string
            image/png:
              schema:
                type: string
                format: byte
components:
  responses:
    badrequest:
      description: BadRequest
      content:
        text/plain:
          schema:
            $ref: "#/components/schemas/badrequest"

  schemas:
    example:
      type: object
      properties:
        value:
          type: string
    badrequest:
      type: string
