openapi: "3.0.0"
info:
  version: 1.0.0
  title: Custom Client Type Example
paths:
  /client:
    get:
      operationId: getClient
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
components:
  schemas:
    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string
