// Package issue1808 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1808

import (
	externalRef0 "github.com/oapi-codegen/oapi-codegen/internal/test/issues/issue-1808/id"
)

// Id defines model for Id.
type Id = externalRef0.Id

// ExternalRef1IdParam defines model for IdParam.
type ExternalRef1IdParam = Id
