// Code generated by specgen from ../../shapes/allof_x_go_type_merged.yaml. DO NOT EDIT.

// Package matrixv3allofxgotypemerged is the allof_x_go_type_merged cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// allOf over a $ref to a schema that x-go-type replaces, and a member with properties of its own.
//
// v3 rejects this shape, so there is no generated code: the test
// checks that generation fails with the expected error.
package matrixv3allofxgotypemerged
