// Code generated by specgen from ../../shapes/nested_nullable_union_31.yaml. DO NOT EDIT.

// Package matrixv2nestednullableunion31 is the nested_nullable_union_31 cell of the aggregate test matrix,
// generated with schema-merging-behavior v2.
//
// A nested oneOf inside an OpenAPI 3.1 nullable anyOf preserves its union payload.
//
// The tests here record how v2 handles this shape. A bug fix may change
// the generated code and the tests, but the tests must not be changed to accept
// a regression: code that generated and worked before must keep doing so. A
// commit that changes them must say why.
package matrixv2nestednullableunion31

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
