// Code generated by specgen from ../../shapes/oneof_discriminator_inline.yaml. DO NOT EDIT.

// Package matrixv1oneofdiscriminatorinline is the oneof_discriminator_inline cell of the aggregate test matrix,
// generated with schema-merging-behavior v1.
//
// A discriminated oneOf whose variants are inline, two pinning their discriminator value with a single-value enum (e05) and one pinning none, which the discriminator doesn't lead to. An inline variant has no name for the mapping, so these failed with "not all schemas were mapped".
//
// The tests here record how v1 handles this shape. A bug fix may change
// the generated code and the tests, but the tests must not be changed to accept
// a regression: code that generated and worked before must keep doing so. A
// commit that changes them must say why.
//
// v1 rejects this shape, so there is no generated code: the test
// checks that generation fails with the expected error.
package matrixv1oneofdiscriminatorinline
