// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package api

import (
	"encoding/json"
)

// Example defines model for example.
type Example struct {
	Value *string `json:"value,omitempty"`
}

// JSONExample200 defines model for POST /json (application/json).
type JSONExample200 = Example

// MultipartExample200 defines model for POST /multipart (multipart/form-data).
type MultipartExample200 = Example

// MultipleRequestAndResponseTypes200JSON defines model for POST /multiple (application/json).
type MultipleRequestAndResponseTypes200JSON = Example

// MultipleRequestAndResponseTypes200ApplicationxWwwFormUrlencoded defines model for POST /multiple (application/x-www-form-urlencoded).
type MultipleRequestAndResponseTypes200ApplicationxWwwFormUrlencoded = Example

// MultipleRequestAndResponseTypes200Imagepng defines model for POST /multiple (image/png).
type MultipleRequestAndResponseTypes200Imagepng = []byte

// MultipleRequestAndResponseTypes200MultipartformData defines model for POST /multiple (multipart/form-data).
type MultipleRequestAndResponseTypes200MultipartformData = Example

// MultipleRequestAndResponseTypes200Textplain defines model for POST /multiple (text/plain).
type MultipleRequestAndResponseTypes200Textplain = string

// ReusableResponses200 defines model for POST /reusable-responses (application/json).
type ReusableResponses200 Reusableresponse

// TextExample200 defines model for POST /text (text/plain).
type TextExample200 = string

// UnknownExample200 defines model for POST /unknown (video/mp4).
type UnknownExample200 = []byte

// UnspecifiedContentType200 defines model for POST /unspecified-content-type (video/*).
type UnspecifiedContentType200 = []byte

// URLEncodedExample200 defines model for POST /urlencoded (application/x-www-form-urlencoded).
type URLEncodedExample200 = Example

// HeadersExample200 defines model for POST /with-headers (application/json).
type HeadersExample200 = Example

// Badrequest defines model for badrequest.
type Badrequest json.RawMessage

// Reusableresponse defines model for reusableresponse.
type Reusableresponse = Example

// MultipleRequestAndResponseTypesTextBody defines parameters for MultipleRequestAndResponseTypes.
type MultipleRequestAndResponseTypesTextBody = string

// TextExampleTextBody defines parameters for TextExample.
type TextExampleTextBody = string

// HeadersExampleParams defines parameters for HeadersExample.
type HeadersExampleParams struct {
	Header1 string `json:"header1"`
	Header2 *int   `json:"header2,omitempty"`
}

// JSONExampleJSONRequestBody defines body for JSONExample for application/json ContentType.
type JSONExampleJSONRequestBody = Example

// MultipartExampleMultipartRequestBody defines body for MultipartExample for multipart/form-data ContentType.
type MultipartExampleMultipartRequestBody = Example

// MultipleRequestAndResponseTypesJSONRequestBody defines body for MultipleRequestAndResponseTypes for application/json ContentType.
type MultipleRequestAndResponseTypesJSONRequestBody = Example

// MultipleRequestAndResponseTypesFormdataRequestBody defines body for MultipleRequestAndResponseTypes for application/x-www-form-urlencoded ContentType.
type MultipleRequestAndResponseTypesFormdataRequestBody = Example

// MultipleRequestAndResponseTypesMultipartRequestBody defines body for MultipleRequestAndResponseTypes for multipart/form-data ContentType.
type MultipleRequestAndResponseTypesMultipartRequestBody = Example

// MultipleRequestAndResponseTypesTextRequestBody defines body for MultipleRequestAndResponseTypes for text/plain ContentType.
type MultipleRequestAndResponseTypesTextRequestBody = MultipleRequestAndResponseTypesTextBody

// ReusableResponsesJSONRequestBody defines body for ReusableResponses for application/json ContentType.
type ReusableResponsesJSONRequestBody = Example

// TextExampleTextRequestBody defines body for TextExample for text/plain ContentType.
type TextExampleTextRequestBody = TextExampleTextBody

// URLEncodedExampleFormdataRequestBody defines body for URLEncodedExample for application/x-www-form-urlencoded ContentType.
type URLEncodedExampleFormdataRequestBody = Example

// HeadersExampleJSONRequestBody defines body for HeadersExample for application/json ContentType.
type HeadersExampleJSONRequestBody = Example
