// Package spec31 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package spec31

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Cat defines model for Cat.
type Cat struct {
	Kind string `json:"kind"`
	Meow *bool  `json:"meow,omitempty"`
}

// ChallengeOpenJson defines model for ChallengeOpenJson.
type ChallengeOpenJson struct {
	Challenger any     `json:"challenger"`
	Id         string  `json:"id"`
	Url        *string `json:"url,omitempty"`
}

// DiscriminatedPet defines model for DiscriminatedPet.
type DiscriminatedPet struct {
	union json.RawMessage
}

// Dog defines model for Dog.
type Dog struct {
	Bark *bool  `json:"bark,omitempty"`
	Kind string `json:"kind"`
}

// NestedNullableUnions defines model for NestedNullableUnions.
type NestedNullableUnions struct {
	Multiple *NestedNullableUnions_Multiple `json:"multiple"`
	Single   *NestedNullableUnions_Single   `json:"single"`
}

// NestedNullableUnions_Multiple defines model for NestedNullableUnions.Multiple.
type NestedNullableUnions_Multiple struct {
	union json.RawMessage
}

// NestedNullableUnions_Single defines model for NestedNullableUnions.Single.
type NestedNullableUnions_Single struct {
	union json.RawMessage
}

// NullOnly defines model for NullOnly.
type NullOnly = any

// Pet defines model for Pet.
type Pet struct {
	// Extras Optional, nullable *unspecified* object (no `properties:`).
	// Regression for the gap where `Schema.Is(...)` strict
	// equality on a 3.1 type-array failed to recognize the
	// primary type as "object", routing the schema away from
	// the unspecified-object code path. Expected shape:
	// `*map[string]any`.
	Extras *map[string]any `json:"extras"`

	// Favorite Nullable discriminated union (`oneOf: [Cat, Dog, null]` with a
	// discriminator). Before this branch's fix to the union-
	// completeness check, the null branch was skipped during
	// mapping construction but still counted toward the
	// expected-mapping count, so generation failed with
	// `discriminator: not all schemas were mapped`. The two real
	// branches must map and the null branch must be tolerated.
	Favorite *DiscriminatedPet `json:"favorite"`

	// Metadata Same as `extras` but with the type-array order reversed.
	// Both orderings must resolve identically; this guards
	// against any code path that inspects only the first
	// element of the type array.
	Metadata *map[string]any `json:"metadata"`

	// Name Required, non-nullable.
	Name string `json:"name"`

	// Nickname Optional, nullable scalar via 3.1 type-array idiom.
	Nickname *string `json:"nickname"`

	// NicknameAnyOf OpenAPI 3.1: a `{"type": "null"}` branch in `anyOf` is a
	// nullability marker, not a separate union variant. Should
	// generate the same shape as `type: ["string","null"]` (i.e.
	// `*string`). Regression for a previous crash with
	// "unhandled Schema type: &[null]".
	NicknameAnyOf *string `json:"nicknameAnyOf"`

	// NicknameOneOf Same as `nicknameAnyOf` but using `oneOf`.
	NicknameOneOf *string `json:"nicknameOneOf"`

	// Owner Optional, nullable inline object.
	Owner *struct {
		Id *string `json:"id,omitempty"`
	} `json:"owner"`

	// Tags Optional, nullable array.
	Tags *[]string `json:"tags"`
}

// RequiredNull defines model for RequiredNull.
type RequiredNull struct {
	Value any `json:"value"`
}

// AsCat returns the union data inside the DiscriminatedPet as a Cat
func (t DiscriminatedPet) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the DiscriminatedPet as the provided Cat
func (t *DiscriminatedPet) FromCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"Cat"}`))
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the DiscriminatedPet, using the provided Cat
func (t *DiscriminatedPet) MergeCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"Cat"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the DiscriminatedPet as a Dog
func (t DiscriminatedPet) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the DiscriminatedPet as the provided Dog
func (t *DiscriminatedPet) FromDog(v Dog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"Dog"}`))
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the DiscriminatedPet, using the provided Dog
func (t *DiscriminatedPet) MergeDog(v Dog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"Dog"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DiscriminatedPet) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DiscriminatedPet) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Cat":
		return t.AsCat()
	case "Dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DiscriminatedPet) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DiscriminatedPet) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCat returns the union data inside the NestedNullableUnions_Multiple as a Cat
func (t NestedNullableUnions_Multiple) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the NestedNullableUnions_Multiple as the provided Cat
func (t *NestedNullableUnions_Multiple) FromCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cat"}`))
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the NestedNullableUnions_Multiple, using the provided Cat
func (t *NestedNullableUnions_Multiple) MergeCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cat"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the NestedNullableUnions_Multiple as a Dog
func (t NestedNullableUnions_Multiple) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the NestedNullableUnions_Multiple as the provided Dog
func (t *NestedNullableUnions_Multiple) FromDog(v Dog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"dog"}`))
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the NestedNullableUnions_Multiple, using the provided Dog
func (t *NestedNullableUnions_Multiple) MergeDog(v Dog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"dog"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NestedNullableUnions_Multiple) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t NestedNullableUnions_Multiple) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cat":
		return t.AsCat()
	case "dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t NestedNullableUnions_Multiple) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NestedNullableUnions_Multiple) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCat returns the union data inside the NestedNullableUnions_Single as a Cat
func (t NestedNullableUnions_Single) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the NestedNullableUnions_Single as the provided Cat
func (t *NestedNullableUnions_Single) FromCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cat"}`))
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the NestedNullableUnions_Single, using the provided Cat
func (t *NestedNullableUnions_Single) MergeCat(v Cat) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cat"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NestedNullableUnions_Single) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t NestedNullableUnions_Single) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cat":
		return t.AsCat()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t NestedNullableUnions_Single) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NestedNullableUnions_Single) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
