// Code generated by specgen from ../../shapes/allof_x_go_type_annotated.yaml. DO NOT EDIT.

// Package matrixv3allofxgotypeannotated is the allof_x_go_type_annotated cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// allOf over a $ref to a schema that x-go-type replaces, and a member that only annotates it.
package matrixv3allofxgotypeannotated

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
