// Code generated by specgen from ../../shapes/properties_additional_properties.yaml. DO NOT EDIT.

// Package matrixv3propertiesadditionalproperties is the properties_additional_properties cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// An object with fixed properties and typed additionalProperties. Not an aggregate, but it gets the same custom JSON methods, and the same envelope handling, as unions do.
package matrixv3propertiesadditionalproperties

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
