// Code generated by oapi-codegen; DO NOT EDIT.

package packagea

import (
	ext_b892eff9 "github.com/oapi-codegen/oapi-codegen-exp/experimental/internal/codegen/test/external_ref/packageb"
)

// #/components/schemas/ObjectA
type ObjectASchemaComponent struct {
	Name    *string               `json:"name,omitempty" form:"name,omitempty"`
	ObjectB *ext_b892eff9.ObjectB `json:"object_b,omitempty" form:"object_b,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectASchemaComponent) ApplyDefaults() {
	if s.ObjectB != nil {
		s.ObjectB.ApplyDefaults()
	}
}

type ObjectA = ObjectASchemaComponent
