// Code generated by specgen from ../../shapes/anyof_oneof.yaml. DO NOT EDIT.

// Package matrixv3anyofoneof is the anyof_oneof cell of the aggregate test matrix,
// generated with schema-merging-behavior v3.
//
// anyOf and oneOf on the same schema, with inline members. Both lists used to name their members <Schema><index> and failed with a duplicate type name (#839).
package matrixv3anyofoneof

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
