// Package packagea provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package packagea

import (
	"bytes"
	"compress/lzw"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/oapi-codegen/oapi-codegen/v2/internal/test/references/multipackage/packageB"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// EnrichedUser defines model for EnrichedUser.
type EnrichedUser struct {
	ExtraField *string              `json:"extra_field,omitempty"`
	Id         string               `json:"id"`
	Roles      *[]externalRef0.Role `json:"roles,omitempty"`
	Username   string               `json:"username"`
}

// ObjectA defines model for ObjectA.
type ObjectA struct {
	Name    *string               `json:"name,omitempty"`
	ObjectB *externalRef0.ObjectB `json:"object_b,omitempty"`
}

// StatusPostPayload defines model for StatusPostPayload.
type StatusPostPayload struct {
	Reason *string                 `json:"reason,omitempty"`
	Status externalRef0.StatusEnum `json:"status"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// Base64 encoded, compressed with lzw, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"APeIGPOmDZw3bsq4oTNHhA6Bc8agKdMmTMOHIoq4kZNGYhkyVeaUkeNQYBg2bJ6YcbhFIAk5ZVbqEDHi",
	"BUGDCBUyfBFxYsU5L+CEGbMmzJkyQr7MgVNmzJeQI0X0YSEQjpw3TOXQSVPmosAyeOjICfPFDFc2ZEqK",
	"oJOHqUMRc8SmcXNG6tS1bcu8fSNGTVM6UrvcfdL3bxC1VrGO3NpVrZswbfRiZOt2ZlyOdKWyEMHX7xg6",
	"X8SofRnzbc2bBxMuBNqTosWgQ4seTbq06RfCnukIsXt3Cp0wdOrMgfImLpQwedi8CZMW48mUMluKIC2T",
	"ps2CqXWy9vgTNlGjSJUydeobuHArMTRXvZqVsVcRMC0iVEtZMly5mfvcrb+38OfAdwn13Wzi2YbbX7th",
	"lFh7XL33WGT05fXWZXPVpV+AsYFH23hfSPEGG5J95UYdbbAkAnNtzCXCZsJF1cVm/FmGn4WbCShbeLWR",
	"91twc2hEoloK/ajDFid+loYdem0211BbISnCi3hVdh9mNIpgo4YF6mjeHOip9ZxKLK2nmFYNqhXXlqPB",
	"VN1p2OW0Gk/cvXYlgTl+UR6PPpao32YwxVFHGjA1R+SZPD4Jo4QzdfYXgDVmSCeHUJGkIHuLlYlRGs0J",
	"FOOUFWoG34eNXUoHRe9RZ9p1OKm2U2vdzYkjhx6C6OmmYcgxVh6etijHgyFGaR+F+d3V55+BmojpiiLo",
	"yquhvvaXm12biTRGHRyxNQV3oQokRBm1jhREHXSgYSa2b4nBLUwkHSolGnTQAQdvSrphxhsOjYjSZoo9",
	"BkcabyErVLgX2ctGHwEB",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and lzw-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := lzw.NewReader(bytes.NewReader(compressed), lzw.LSB, 8)
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read lzw: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close lzw reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../packageB/spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
