// Package issue1767 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue1767

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Alarm Alarm Information
type Alarm struct {
	// UnderscoreId Identifier of the Alarm.
	UnderscoreId *openapi_types.UUID `json:"_id,omitempty"`

	// Id Identifier of the Alarm.
	Id *openapi_types.UUID `json:"id,omitempty"`
}
