// Code generated by specgen from ../../shapes/allof_nullable_decorator.yaml. DO NOT EDIT.

// Package matrixv1allofnullabledecorator is the allof_nullable_decorator cell of the aggregate test matrix,
// generated with schema-merging-behavior v1.
//
// allOf over a $ref and `nullable: true`, the OpenAPI 3.0 nullable-$ref idiom (#1898).
//
// The tests here record how v1 handles this shape. A bug fix may change
// the generated code and the tests, but the tests must not be changed to accept
// a regression: code that generated and worked before must keep doing so. A
// commit that changes them must say why.
package matrixv1allofnullabledecorator

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml spec.yaml
