// Code generated by oapi-codegen; DO NOT EDIT.

package packageb

// #/components/schemas/ObjectB
type ObjectBSchemaComponent struct {
	Name *string `json:"name,omitempty" form:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectBSchemaComponent) ApplyDefaults() {
}

type ObjectB = ObjectBSchemaComponent
