openapi: "3.0.0"
info:
  version: 1.0.0
  title: prefer-skip-optional-pointer
components:
  schemas:
    Client:
      type: object
      required:
        - name
      properties:
        name:
          description: This field is required, so will never have an optional pointer.
          type: string
        id:
          description: This field is optional, but the `prefer-skip-optional-pointer` Output Option ensures that this should not have an optional pointer.
          type: number
    ClientWithExtension:
      type: object
      required:
        - name
      properties:
        name:
          description: This field is required, so will never have an optional pointer.
          type: string
        id:
          description: This field is optional, but the `prefer-skip-optional-pointer` Output Option ensures that this should not have an optional pointer.
          type: number
        pointer_id:
          type: number
          description: This field should have an optional pointer, as the field-level definition of `x-go-type-skip-optional-pointer` overrides the `prefer-skip-optional-pointer` Output Option.
          # NOTE that this overrides the global preference
          x-go-type-skip-optional-pointer: false
    NestedType:
      type: object
      properties:
        client:
          description: This field is optional, but the `prefer-skip-optional-pointer` Output Option ensures that this should not have an optional pointer.
          $ref: '#/components/schemas/Client'
