openapi: "3.0.0"
info:
  version: 1.0.0
  title: prefer-skip-optional-pointer
components:
  schemas:
    Client:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        id:
          type: number
    ClientWithExtension:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        id:
          type: number
        pointer_id:
          type: number
          # NOTE that this overrides the global preference
          x-go-type-skip-optional-pointer: false
