// Package issue2091 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package issue2091

// TypeWithNullable defines model for TypeWithNullable.
type TypeWithNullable struct {
	Newfield *string `json:"newfield"`
}
