// Package fibermid provides middleware and helper functions for the Fiber web
// framework. It supports header-based API version routing, response helpers,
// and a generic registration entry point that wires repositories →
// controllers → handlers and registers them under a version prefix.
//
// This package consolidates the versioning runtime, request-scoped context
// keys, and HTTP error taxonomy that fibermid relies on into a single
// dependency-light module.
package fibermid

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/rs/zerolog"
)

const LatestVersion = "latest"

// Context keys used by Init to stash per-request config and logger into the
// Fiber context. These are exposed so downstream packages can retrieve them
// without re-declaring private keys.
type contextKey string

var (
	CfgCtxKey     contextKey = "config"
	LogHelpCtxKey contextKey = "loghelp"
)

// Init wires per-request logging and stashes the config + a request-scoped
// logger into the Fiber context. The generic type parameter lets callers pass
// any config struct without this package depending on it.
func Init[T any](app *fiber.App, ctx context.Context, cfg T, log *zerolog.Logger) {
	app.Use(func(c *fiber.Ctx) error {
		log.Debug().Fields(map[string]interface{}{
			"request_method": c.Method(),
			"request_url":    c.OriginalURL(),
			"request_id":     c.Context().ID(),
			"headers":        c.GetReqHeaders(),
			"body":           string(c.Body()),
		}).Msg("request received")

		l := log.With().Uint64("request_id", c.Context().ID()).Logger()

		c.Context().SetUserValue(CfgCtxKey, cfg)
		c.Context().SetUserValue(LogHelpCtxKey, &l)

		return c.Next()
	})
}

// ExtractVersion parses an Accept-style header to extract a `version=` parameter.
// When present, the version is returned with a leading "v" (e.g., "v1"). When
// absent it returns "".
func ExtractVersion(header string) string {
	parts := strings.Split(header, ";")
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if strings.HasPrefix(part, "version=") {
			version := strings.TrimPrefix(part, "version=")
			return "v" + version
		}
	}
	return ""
}

// RegisterAPIVersion wires a repo → controller → handler chain for one API
// version, registers the handler routes via the caller-supplied
// registerHandlers function (typically generated by oapi-codegen), and merges
// the resulting route map into the shared apiHandlers table that VersionRouter
// dispatches against.
func RegisterAPIVersion[TRepo any, TController any, THandler any](
	app *fiber.App,
	repo TRepo,
	version string,
	newController func(TRepo) TController,
	newHandler func(TController) THandler,
	registerHandlers func(*fiber.App, THandler, string) map[string]map[string]fiber.Handler,
	apiHandlers map[string]map[string]fiber.Handler,
) {
	ctrlr := newController(repo)
	handler := newHandler(ctrlr)
	handlerMap := registerHandlers(app, handler, version)
	AppendToHandlers(apiHandlers, handlerMap)
}

// AppendToHandlers merges the per-route inner maps from m into apiHandlers.
// Existing entries for the same path are preserved (per-method inner keys are
// merged, not overwritten) so v1 and v2 can coexist on the same shared map.
func AppendToHandlers(apiHandlers map[string]map[string]fiber.Handler, m map[string]map[string]fiber.Handler) {
	if apiHandlers == nil {
		// caller should have passed a non-nil map; create one defensively.
		apiHandlers = make(map[string]map[string]fiber.Handler)
	}
	for key, handlerMap := range m {
		if apiHandlers[key] == nil {
			apiHandlers[key] = make(map[string]fiber.Handler)
		}
		for handlerKey, handler := range handlerMap {
			apiHandlers[key][handlerKey] = handler
		}
	}
}

// MountVersionedRoutes binds Fiber routes at the BARE paths derived from
// `apiHandlers` (which is populated by oapi-codegen-emitted
// `RegisterHandlerVersionsWithOptions` calls). External clients see only
// bare paths (e.g. `/events`, `/events/:id`); the registered Fiber handler
// is a dispatcher that picks the per-version handler from `apiHandlers`
// based on the `API-Version` (or `X-API-Version`) request header. When the
// header is absent, defaultVersion is used.
//
// `apiHandlers` is the standard map shape produced by the fork's Fiber
// templates:
//
//	"/v1/events/:id" -> { "GET": wrapper.GetEvent, "PUT": wrapper.UpdateEvent }
//	"/v2/events/:id" -> { "GET": wrapper.GetEvent, "PUT": wrapper.UpdateEvent }
//	"/latest/events/:id" -> ... (set by the templates as an alias)
//
// Path parameters are handled correctly here because the bare-path Fiber
// route does the matching: the dispatcher receives a `*fiber.Ctx` whose
// `c.Params(...)` is already populated, and it forwards that same ctx to
// the per-version wrapper. The wrapper's `c.Params("id")` reads the value
// the bare-path route extracted.
//
// Typical usage in a service's server.go:
//
//	apiHandlers := make(map[string]map[string]fiber.Handler)
//	v1.RegisterHandlerVersionsWithOptions(app, v1Handler, "v1", apiHandlers, v1.FiberServerOptions{})
//	v2.RegisterHandlerVersionsWithOptions(app, v2Handler, "v2", apiHandlers, v2.FiberServerOptions{})
//	fibermid.MountVersionedRoutes(app, apiHandlers, "v1")
//
// This binds `/events`, `/events/:id`, `/versions` etc. as the only
// externally visible URLs. `/v1/...` and `/v2/...` are NOT registered as
// Fiber routes; a request to those will 404.
func MountVersionedRoutes(app *fiber.App, apiHandlers map[string]map[string]fiber.Handler, defaultVersion string) {
	defaultVersion = strings.TrimSpace(defaultVersion)
	if defaultVersion != "" && !strings.HasPrefix(defaultVersion, "v") {
		defaultVersion = "v" + defaultVersion
	}

	type bareKey struct {
		path   string
		method string
	}
	seen := map[bareKey]struct{}{}

	for vPath, methods := range apiHandlers {
		barePath, ok := stripVersionPrefix(vPath)
		if !ok {
			// e.g. apiHandlers contains keys without an embedded version
			// segment; skip those rather than registering at the wrong path.
			continue
		}
		for method := range methods {
			k := bareKey{path: barePath, method: method}
			if _, dup := seen[k]; dup {
				continue
			}
			seen[k] = struct{}{}

			barePath, method := barePath, method // capture
			app.Add(method, barePath, func(c *fiber.Ctx) error {
				ver := c.Get("API-Version")
				if ver == "" {
					ver = c.Get("X-API-Version")
				}
				if ver == "" {
					ver = defaultVersion
				}
				ver = strings.TrimSpace(ver)
				if ver != "" && !strings.HasPrefix(ver, "v") && ver != LatestVersion {
					ver = "v" + ver
				}
				if ver != "" {
					if h := lookupHandler(apiHandlers, "/"+ver+barePath, method); h != nil {
						return h(c)
					}
				}
				// Fall back to whatever the templates registered as
				// `/latest/<barePath>` (typically the highest version that
				// registered).
				if h := lookupHandler(apiHandlers, "/"+LatestVersion+barePath, method); h != nil {
					return h(c)
				}
				return c.Status(fiber.StatusNotFound).SendString("api version not available for route")
			})
		}
	}
}

// stripVersionPrefix turns "/v1/events/:id" → "/events/:id" (true). Returns
// (path, false) when path is not in the expected `/<segment>/...` shape.
func stripVersionPrefix(p string) (string, bool) {
	if len(p) < 2 || p[0] != '/' {
		return "", false
	}
	rest := p[1:]
	i := strings.IndexByte(rest, '/')
	if i < 0 {
		return "", false
	}
	return rest[i:], true // rest[i] is the leading '/'
}

func lookupHandler(apiHandlers map[string]map[string]fiber.Handler, key, method string) fiber.Handler {
	routes, ok := apiHandlers[key]
	if !ok {
		return nil
	}
	if h, ok := routes[method]; ok {
		return h
	}
	return nil
}

// VersionPathMiddleware returns a Fiber middleware that resolves the
// effective API version from the `API-Version` (or `X-API-Version`) header
// and rewrites the request path to add a `/<version>` prefix when the
// request didn't already carry one. After rewriting, it calls
// c.RestartRouting() so Fiber's normal route tree (with proper path-param
// support) dispatches the request to the version-prefixed handler.
//
// Deprecated: this exposes `/v<n>/...` URLs publicly via the registered
// per-version routes. Prefer MountVersionedRoutes (header-only,
// bare-path-only) for new services that want to keep the URL space
// version-free.
//
// Behavior:
//   - When the request path already starts with `/v<digits>/` (or equals
//     `/v<digits>`), the middleware passes through unchanged.
//   - Paths whose exact value is in skipPaths (e.g. `/healthchecks`) pass
//     through unchanged.
//   - Otherwise, the middleware reads the version from `API-Version` (or
//     `X-API-Version`), falling back to defaultVersion if neither is set,
//     prepends `/<version>` to the path, and restarts routing.
func VersionPathMiddleware(defaultVersion string, skipPaths ...string) fiber.Handler {
	skipSet := make(map[string]struct{}, len(skipPaths))
	for _, p := range skipPaths {
		skipSet[p] = struct{}{}
	}
	return func(c *fiber.Ctx) error {
		p := c.Path()
		if _, ok := skipSet[p]; ok {
			return c.Next()
		}
		// already prefixed: /v<digits>(/...)? — treat as version-explicit
		if len(p) >= 2 && p[0] == '/' && p[1] == 'v' {
			i := 2
			for i < len(p) && p[i] >= '0' && p[i] <= '9' {
				i++
			}
			if i > 2 && (i == len(p) || p[i] == '/') {
				return c.Next()
			}
		}

		version := c.Get("API-Version")
		if version == "" {
			version = c.Get("X-API-Version")
		}
		if version == "" {
			version = defaultVersion
		}
		version = strings.TrimSpace(version)
		if version != "" && !strings.HasPrefix(version, "v") {
			version = "v" + version
		}
		if version == "" {
			// nothing to do; let it 404 naturally if the path is unknown.
			return c.Next()
		}

		c.Path("/" + version + p)
		return c.RestartRouting()
	}
}

// VersionRouter dispatches the request to the handler registered under the
// versioned key matching the incoming `API-Version` header (or the deprecated
// `X-API-Version` / Accept-version fallbacks).
//
// Deprecated: this dispatcher uses literal map-key lookup, so the keys
// produced by the registerHandlers callback must contain the literal request
// path — path-parameter routes (e.g. "/v1/events/:id") are NOT
// pattern-matched here, and a request like `GET /events/1` with
// `API-Version: v1` will fall through to "versioned route not found".
// Use VersionPathMiddleware instead.
func VersionRouter(c *fiber.Ctx, apiHandlers map[string]map[string]fiber.Handler) error {
	version := c.Get("API-Version")
	if version == "" {
		version = c.Get("X-API-Version")
	}
	if version == "" {
		ct := c.Get("Accept")
		version = ExtractVersion(ct)
	}

	version = strings.TrimSpace(version)
	if version != "" && version != LatestVersion {
		if !strings.HasPrefix(version, "v") {
			version = "v" + version
		}
	}
	if version == "" {
		version = LatestVersion
	}

	key := "/" + version + c.Path()
	if routes, exists := apiHandlers[key]; exists {
		methodKey := c.Method() + ":" + key
		if handler, ok := routes[methodKey]; ok {
			return handler(c)
		}
		if handler, ok := routes[key]; ok {
			return handler(c)
		}
		if len(routes) == 1 {
			for _, handler := range routes {
				return handler(c)
			}
		}
	}

	return c.Status(fiber.StatusNotFound).SendString("versioned route not found")
}

// SetResponse marshals body as JSON and writes it with the given status code.
func SetResponse(c *fiber.Ctx, body any, status int) error {
	payload, _ := json.Marshal(body)
	c.Response().Header.SetContentType("application/json")
	c.Response().SetBody(payload)
	return c.SendStatus(status)
}

// Error is a generic error response shape used by HandleResponse.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Response is a generic response envelope wrapping data and an optional error.
type Response struct {
	Data  any    `json:"data"`
	Error *Error `json:"error,omitempty"`
}

// HandleResponse writes a Response envelope. On error, the HTTP status code is
// derived from the error type via GetErrorCode.
func HandleResponse(c *fiber.Ctx, obj any, err error) error {
	if err != nil {
		code := GetErrorCode(err)
		return SetResponse(c, Response{
			Data: obj,
			Error: &Error{
				Code:    code,
				Message: err.Error(),
			},
		}, code)
	}

	return SetResponse(c, Response{Data: obj}, http.StatusOK)
}

// SetAnyResponse marshals the typed err value and writes it with the given
// status code. Useful when the caller wants the wire shape to match a typed
// generated error rather than fibermid's default Error envelope.
func SetAnyResponse[T any](c *fiber.Ctx, err T, status int) error {
	errorData, _ := json.Marshal(err)
	c.Response().Header.SetContentType("application/json")
	c.Response().SetBody(errorData)
	return c.SendStatus(status)
}

// HTTP error taxonomy. These wrap an underlying error and map to specific
// HTTP status codes via GetErrorCode. Inlined from the former
// github.com/wayleadr/api-commons/httperror package.

const errFormat = "[%d] %v"

// InvalidInput is an error type for invalid input (400).
type InvalidInput struct {
	Err error
}

// Unauthorized is an error type for authorization errors (401).
type Unauthorized struct {
	Err error
}

// NotFound is an error type for not found (404).
type NotFound struct {
	Err error
}

// TransientError is an error type for transient errors (503).
type TransientError struct {
	Err error
}

// InternalServer is an error type for internal server errors (500).
type InternalServer struct {
	Err error
}

func (t InvalidInput) Error() string   { return getErrorMsg(t, t.Err) }
func (t Unauthorized) Error() string   { return getErrorMsg(t, t.Err) }
func (t NotFound) Error() string       { return getErrorMsg(t, t.Err) }
func (t TransientError) Error() string { return getErrorMsg(t, t.Err) }
func (t InternalServer) Error() string { return getErrorMsg(t, t.Err) }

func getErrorMsg(httpErr error, err error) string {
	return fmt.Sprintf(errFormat, GetErrorCode(httpErr), err)
}

// GetErrorCode maps an error to its HTTP status code based on the typed
// errors above; unknown errors default to 500.
func GetErrorCode(err error) int {
	switch {
	case errors.As(err, &InvalidInput{}):
		return http.StatusBadRequest
	case errors.As(err, &Unauthorized{}):
		return http.StatusUnauthorized
	case errors.As(err, &NotFound{}):
		return http.StatusNotFound
	case errors.As(err, &TransientError{}):
		return http.StatusServiceUnavailable
	default:
		return http.StatusInternalServerError
	}
}
