// Package head_digit_of_operation_id provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package head_digit_of_operation_id
