// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/wayleadr/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package api

import (
	"github.com/gofiber/fiber/v2"
	fibermid "github.com/wayleadr/oapi-codegen/v2/pkg/fibermid"
)

// Pong defines model for Pong.
type Pong struct {
	// Ping Example: pong
	Ping string `json:"ping"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ping)
	GetPing(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetPing(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/ping", wrapper.GetPing)

}

// RegisterHandlerVersions registers the routes into apiHandlers under the given
// version, for dispatch by fibermid.MountVersionedRoutes.
func RegisterHandlerVersions(
	router fiber.Router,
	si ServerInterface,
	version string,
	apiHandlers map[string]map[string]fiber.Handler,
) map[string]map[string]fiber.Handler {
	return RegisterHandlerVersionsWithOptions(router, si, version, apiHandlers, FiberServerOptions{})
}

// RegisterHandlerVersionsWithOptions registers the routes into apiHandlers under
// the given version, with additional options.
func RegisterHandlerVersionsWithOptions(
	router fiber.Router,
	si ServerInterface,
	version string,
	apiHandlers map[string]map[string]fiber.Handler,
	options FiberServerOptions,
) map[string]map[string]fiber.Handler {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	if apiHandlers == nil {
		apiHandlers = make(map[string]map[string]fiber.Handler)
	}
	var versionedPath, latestPath string

	// /ping
	versionedPath = "/" + version + "/ping"
	if apiHandlers[versionedPath] == nil {
		apiHandlers[versionedPath] = make(map[string]fiber.Handler)
	}

	latestPath = "/" + fibermid.LatestVersion + "/ping"
	if apiHandlers[latestPath] == nil {
		apiHandlers[latestPath] = make(map[string]fiber.Handler)
	}

	apiHandlers[versionedPath]["GET"] = wrapper.GetPing
	apiHandlers[latestPath]["GET"] = wrapper.GetPing

	return apiHandlers
}
